/*
Libre Graph API

Testing DrivesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package libregraph

import (
	"context"
	openapiclient "github.com/owncloud/libre-graph-api-go"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_libregraph_DrivesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DrivesAPIService CreateDrive", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.DrivesAPI.CreateDrive(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DrivesAPIService DeleteDrive", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var driveId string

		httpRes, err := apiClient.DrivesAPI.DeleteDrive(context.Background(), driveId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DrivesAPIService GetDrive", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var driveId string

		resp, httpRes, err := apiClient.DrivesAPI.GetDrive(context.Background(), driveId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DrivesAPIService UpdateDrive", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var driveId string

		resp, httpRes, err := apiClient.DrivesAPI.UpdateDrive(context.Background(), driveId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
