/*
Libre Graph API

Testing EducationClassAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package libregraph

import (
	"context"
	openapiclient "github.com/owncloud/libre-graph-api-go"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_libregraph_EducationClassAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test EducationClassAPIService AddUserToClass", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var classId string

		httpRes, err := apiClient.EducationClassAPI.AddUserToClass(context.Background(), classId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EducationClassAPIService CreateClass", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.EducationClassAPI.CreateClass(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EducationClassAPIService DeleteClass", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var classId string

		httpRes, err := apiClient.EducationClassAPI.DeleteClass(context.Background(), classId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EducationClassAPIService DeleteUserFromClass", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var classId string
		var userId string

		httpRes, err := apiClient.EducationClassAPI.DeleteUserFromClass(context.Background(), classId, userId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EducationClassAPIService GetClass", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var classId string

		resp, httpRes, err := apiClient.EducationClassAPI.GetClass(context.Background(), classId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EducationClassAPIService ListClassMembers", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var classId string

		resp, httpRes, err := apiClient.EducationClassAPI.ListClassMembers(context.Background(), classId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EducationClassAPIService ListClasses", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.EducationClassAPI.ListClasses(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EducationClassAPIService UpdateClass", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var classId string

		resp, httpRes, err := apiClient.EducationClassAPI.UpdateClass(context.Background(), classId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
