/*
 * Open Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// OpenGraphDriveItem struct for OpenGraphDriveItem
type OpenGraphDriveItem struct {
	OpenGraphBaseItem
	// The content stream, if the item represents a file.
	Content *string `json:"content,omitempty"`
	// An eTag for the content of the item. This eTag is not changed if only the metadata is changed. Note This property is not returned if the item is a folder. Read-only.
	CTag *string `json:"cTag,omitempty"`
	// Information about the deleted state of the item. Read-only.
	Deleted *OpenGraphDeleted `json:"deleted,omitempty"`
	// File metadata, if the item is a file. Read-only.
	File *OpenGraphFile `json:"file,omitempty"`
	// File system information on client. Read-write.
	FileSystemInfo *OpenGraphFileSystemInfo `json:"fileSystemInfo,omitempty"`
	// Folder metadata, if the item is a folder. Read-only.
	Folder *OpenGraphFolder `json:"folder,omitempty"`
	// Image metadata, if the item is an image. Read-only.
	Image *OpenGraphImage `json:"image,omitempty"`
	// If this property is non-null, it indicates that the driveItem is the top-most driveItem in the drive.
	Root *map[string]interface{} `json:"root,omitempty"`
	// Size of the item in bytes. Read-only.
	Size *int64 `json:"size,omitempty"`
	// WebDAV compatible URL for the item. Read-only.
	WebDavUrl *string `json:"webDavUrl,omitempty"`
	// Collection containing Item objects for the immediate children of Item. Only items representing folders have children. Read-only. Nullable.
	Children *[]OpenGraphDriveItem `json:"children,omitempty"`
}

// NewOpenGraphDriveItem instantiates a new OpenGraphDriveItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenGraphDriveItem() *OpenGraphDriveItem {
	this := OpenGraphDriveItem{}
	return &this
}

// NewOpenGraphDriveItemWithDefaults instantiates a new OpenGraphDriveItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenGraphDriveItemWithDefaults() *OpenGraphDriveItem {
	this := OpenGraphDriveItem{}
	return &this
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *OpenGraphDriveItem) GetContent() string {
	if o == nil || o.Content == nil {
		var ret string
		return ret
	}
	return *o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenGraphDriveItem) GetContentOk() (*string, bool) {
	if o == nil || o.Content == nil {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *OpenGraphDriveItem) HasContent() bool {
	if o != nil && o.Content != nil {
		return true
	}

	return false
}

// SetContent gets a reference to the given string and assigns it to the Content field.
func (o *OpenGraphDriveItem) SetContent(v string) {
	o.Content = &v
}

// GetCTag returns the CTag field value if set, zero value otherwise.
func (o *OpenGraphDriveItem) GetCTag() string {
	if o == nil || o.CTag == nil {
		var ret string
		return ret
	}
	return *o.CTag
}

// GetCTagOk returns a tuple with the CTag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenGraphDriveItem) GetCTagOk() (*string, bool) {
	if o == nil || o.CTag == nil {
		return nil, false
	}
	return o.CTag, true
}

// HasCTag returns a boolean if a field has been set.
func (o *OpenGraphDriveItem) HasCTag() bool {
	if o != nil && o.CTag != nil {
		return true
	}

	return false
}

// SetCTag gets a reference to the given string and assigns it to the CTag field.
func (o *OpenGraphDriveItem) SetCTag(v string) {
	o.CTag = &v
}

// GetDeleted returns the Deleted field value if set, zero value otherwise.
func (o *OpenGraphDriveItem) GetDeleted() OpenGraphDeleted {
	if o == nil || o.Deleted == nil {
		var ret OpenGraphDeleted
		return ret
	}
	return *o.Deleted
}

// GetDeletedOk returns a tuple with the Deleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenGraphDriveItem) GetDeletedOk() (*OpenGraphDeleted, bool) {
	if o == nil || o.Deleted == nil {
		return nil, false
	}
	return o.Deleted, true
}

// HasDeleted returns a boolean if a field has been set.
func (o *OpenGraphDriveItem) HasDeleted() bool {
	if o != nil && o.Deleted != nil {
		return true
	}

	return false
}

// SetDeleted gets a reference to the given OpenGraphDeleted and assigns it to the Deleted field.
func (o *OpenGraphDriveItem) SetDeleted(v OpenGraphDeleted) {
	o.Deleted = &v
}

// GetFile returns the File field value if set, zero value otherwise.
func (o *OpenGraphDriveItem) GetFile() OpenGraphFile {
	if o == nil || o.File == nil {
		var ret OpenGraphFile
		return ret
	}
	return *o.File
}

// GetFileOk returns a tuple with the File field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenGraphDriveItem) GetFileOk() (*OpenGraphFile, bool) {
	if o == nil || o.File == nil {
		return nil, false
	}
	return o.File, true
}

// HasFile returns a boolean if a field has been set.
func (o *OpenGraphDriveItem) HasFile() bool {
	if o != nil && o.File != nil {
		return true
	}

	return false
}

// SetFile gets a reference to the given OpenGraphFile and assigns it to the File field.
func (o *OpenGraphDriveItem) SetFile(v OpenGraphFile) {
	o.File = &v
}

// GetFileSystemInfo returns the FileSystemInfo field value if set, zero value otherwise.
func (o *OpenGraphDriveItem) GetFileSystemInfo() OpenGraphFileSystemInfo {
	if o == nil || o.FileSystemInfo == nil {
		var ret OpenGraphFileSystemInfo
		return ret
	}
	return *o.FileSystemInfo
}

// GetFileSystemInfoOk returns a tuple with the FileSystemInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenGraphDriveItem) GetFileSystemInfoOk() (*OpenGraphFileSystemInfo, bool) {
	if o == nil || o.FileSystemInfo == nil {
		return nil, false
	}
	return o.FileSystemInfo, true
}

// HasFileSystemInfo returns a boolean if a field has been set.
func (o *OpenGraphDriveItem) HasFileSystemInfo() bool {
	if o != nil && o.FileSystemInfo != nil {
		return true
	}

	return false
}

// SetFileSystemInfo gets a reference to the given OpenGraphFileSystemInfo and assigns it to the FileSystemInfo field.
func (o *OpenGraphDriveItem) SetFileSystemInfo(v OpenGraphFileSystemInfo) {
	o.FileSystemInfo = &v
}

// GetFolder returns the Folder field value if set, zero value otherwise.
func (o *OpenGraphDriveItem) GetFolder() OpenGraphFolder {
	if o == nil || o.Folder == nil {
		var ret OpenGraphFolder
		return ret
	}
	return *o.Folder
}

// GetFolderOk returns a tuple with the Folder field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenGraphDriveItem) GetFolderOk() (*OpenGraphFolder, bool) {
	if o == nil || o.Folder == nil {
		return nil, false
	}
	return o.Folder, true
}

// HasFolder returns a boolean if a field has been set.
func (o *OpenGraphDriveItem) HasFolder() bool {
	if o != nil && o.Folder != nil {
		return true
	}

	return false
}

// SetFolder gets a reference to the given OpenGraphFolder and assigns it to the Folder field.
func (o *OpenGraphDriveItem) SetFolder(v OpenGraphFolder) {
	o.Folder = &v
}

// GetImage returns the Image field value if set, zero value otherwise.
func (o *OpenGraphDriveItem) GetImage() OpenGraphImage {
	if o == nil || o.Image == nil {
		var ret OpenGraphImage
		return ret
	}
	return *o.Image
}

// GetImageOk returns a tuple with the Image field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenGraphDriveItem) GetImageOk() (*OpenGraphImage, bool) {
	if o == nil || o.Image == nil {
		return nil, false
	}
	return o.Image, true
}

// HasImage returns a boolean if a field has been set.
func (o *OpenGraphDriveItem) HasImage() bool {
	if o != nil && o.Image != nil {
		return true
	}

	return false
}

// SetImage gets a reference to the given OpenGraphImage and assigns it to the Image field.
func (o *OpenGraphDriveItem) SetImage(v OpenGraphImage) {
	o.Image = &v
}

// GetRoot returns the Root field value if set, zero value otherwise.
func (o *OpenGraphDriveItem) GetRoot() map[string]interface{} {
	if o == nil || o.Root == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.Root
}

// GetRootOk returns a tuple with the Root field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenGraphDriveItem) GetRootOk() (*map[string]interface{}, bool) {
	if o == nil || o.Root == nil {
		return nil, false
	}
	return o.Root, true
}

// HasRoot returns a boolean if a field has been set.
func (o *OpenGraphDriveItem) HasRoot() bool {
	if o != nil && o.Root != nil {
		return true
	}

	return false
}

// SetRoot gets a reference to the given map[string]interface{} and assigns it to the Root field.
func (o *OpenGraphDriveItem) SetRoot(v map[string]interface{}) {
	o.Root = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *OpenGraphDriveItem) GetSize() int64 {
	if o == nil || o.Size == nil {
		var ret int64
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenGraphDriveItem) GetSizeOk() (*int64, bool) {
	if o == nil || o.Size == nil {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *OpenGraphDriveItem) HasSize() bool {
	if o != nil && o.Size != nil {
		return true
	}

	return false
}

// SetSize gets a reference to the given int64 and assigns it to the Size field.
func (o *OpenGraphDriveItem) SetSize(v int64) {
	o.Size = &v
}

// GetWebDavUrl returns the WebDavUrl field value if set, zero value otherwise.
func (o *OpenGraphDriveItem) GetWebDavUrl() string {
	if o == nil || o.WebDavUrl == nil {
		var ret string
		return ret
	}
	return *o.WebDavUrl
}

// GetWebDavUrlOk returns a tuple with the WebDavUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenGraphDriveItem) GetWebDavUrlOk() (*string, bool) {
	if o == nil || o.WebDavUrl == nil {
		return nil, false
	}
	return o.WebDavUrl, true
}

// HasWebDavUrl returns a boolean if a field has been set.
func (o *OpenGraphDriveItem) HasWebDavUrl() bool {
	if o != nil && o.WebDavUrl != nil {
		return true
	}

	return false
}

// SetWebDavUrl gets a reference to the given string and assigns it to the WebDavUrl field.
func (o *OpenGraphDriveItem) SetWebDavUrl(v string) {
	o.WebDavUrl = &v
}

// GetChildren returns the Children field value if set, zero value otherwise.
func (o *OpenGraphDriveItem) GetChildren() []OpenGraphDriveItem {
	if o == nil || o.Children == nil {
		var ret []OpenGraphDriveItem
		return ret
	}
	return *o.Children
}

// GetChildrenOk returns a tuple with the Children field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenGraphDriveItem) GetChildrenOk() (*[]OpenGraphDriveItem, bool) {
	if o == nil || o.Children == nil {
		return nil, false
	}
	return o.Children, true
}

// HasChildren returns a boolean if a field has been set.
func (o *OpenGraphDriveItem) HasChildren() bool {
	if o != nil && o.Children != nil {
		return true
	}

	return false
}

// SetChildren gets a reference to the given []OpenGraphDriveItem and assigns it to the Children field.
func (o *OpenGraphDriveItem) SetChildren(v []OpenGraphDriveItem) {
	o.Children = &v
}

func (o OpenGraphDriveItem) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedOpenGraphBaseItem, errOpenGraphBaseItem := json.Marshal(o.OpenGraphBaseItem)
	if errOpenGraphBaseItem != nil {
		return []byte{}, errOpenGraphBaseItem
	}
	errOpenGraphBaseItem = json.Unmarshal([]byte(serializedOpenGraphBaseItem), &toSerialize)
	if errOpenGraphBaseItem != nil {
		return []byte{}, errOpenGraphBaseItem
	}
	if o.Content != nil {
		toSerialize["content"] = o.Content
	}
	if o.CTag != nil {
		toSerialize["cTag"] = o.CTag
	}
	if o.Deleted != nil {
		toSerialize["deleted"] = o.Deleted
	}
	if o.File != nil {
		toSerialize["file"] = o.File
	}
	if o.FileSystemInfo != nil {
		toSerialize["fileSystemInfo"] = o.FileSystemInfo
	}
	if o.Folder != nil {
		toSerialize["folder"] = o.Folder
	}
	if o.Image != nil {
		toSerialize["image"] = o.Image
	}
	if o.Root != nil {
		toSerialize["root"] = o.Root
	}
	if o.Size != nil {
		toSerialize["size"] = o.Size
	}
	if o.WebDavUrl != nil {
		toSerialize["webDavUrl"] = o.WebDavUrl
	}
	if o.Children != nil {
		toSerialize["children"] = o.Children
	}
	return json.Marshal(toSerialize)
}

type NullableOpenGraphDriveItem struct {
	value *OpenGraphDriveItem
	isSet bool
}

func (v NullableOpenGraphDriveItem) Get() *OpenGraphDriveItem {
	return v.value
}

func (v *NullableOpenGraphDriveItem) Set(val *OpenGraphDriveItem) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenGraphDriveItem) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenGraphDriveItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenGraphDriveItem(val *OpenGraphDriveItem) *NullableOpenGraphDriveItem {
	return &NullableOpenGraphDriveItem{value: val, isSet: true}
}

func (v NullableOpenGraphDriveItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenGraphDriveItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


