/*
 * Open Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// OpenGraphFile struct for OpenGraphFile
type OpenGraphFile struct {
	// Hashes of the file's binary content, if available. Read-only.
	Hashes NullableAnyOfopenGraphHashes `json:"hashes,omitempty"`
	// The MIME type for the file. This is determined by logic on the server and might not be the value provided when the file was uploaded. Read-only.
	MimeType NullableString `json:"mimeType,omitempty"`
	ProcessingMetadata NullableBool `json:"processingMetadata,omitempty"`
}

// NewOpenGraphFile instantiates a new OpenGraphFile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenGraphFile() *OpenGraphFile {
	this := OpenGraphFile{}
	return &this
}

// NewOpenGraphFileWithDefaults instantiates a new OpenGraphFile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenGraphFileWithDefaults() *OpenGraphFile {
	this := OpenGraphFile{}
	return &this
}

// GetHashes returns the Hashes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenGraphFile) GetHashes() AnyOfopenGraphHashes {
	if o == nil || o.Hashes.Get() == nil {
		var ret AnyOfopenGraphHashes
		return ret
	}
	return *o.Hashes.Get()
}

// GetHashesOk returns a tuple with the Hashes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenGraphFile) GetHashesOk() (*AnyOfopenGraphHashes, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Hashes.Get(), o.Hashes.IsSet()
}

// HasHashes returns a boolean if a field has been set.
func (o *OpenGraphFile) HasHashes() bool {
	if o != nil && o.Hashes.IsSet() {
		return true
	}

	return false
}

// SetHashes gets a reference to the given NullableAnyOfopenGraphHashes and assigns it to the Hashes field.
func (o *OpenGraphFile) SetHashes(v AnyOfopenGraphHashes) {
	o.Hashes.Set(&v)
}
// SetHashesNil sets the value for Hashes to be an explicit nil
func (o *OpenGraphFile) SetHashesNil() {
	o.Hashes.Set(nil)
}

// UnsetHashes ensures that no value is present for Hashes, not even an explicit nil
func (o *OpenGraphFile) UnsetHashes() {
	o.Hashes.Unset()
}

// GetMimeType returns the MimeType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenGraphFile) GetMimeType() string {
	if o == nil || o.MimeType.Get() == nil {
		var ret string
		return ret
	}
	return *o.MimeType.Get()
}

// GetMimeTypeOk returns a tuple with the MimeType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenGraphFile) GetMimeTypeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.MimeType.Get(), o.MimeType.IsSet()
}

// HasMimeType returns a boolean if a field has been set.
func (o *OpenGraphFile) HasMimeType() bool {
	if o != nil && o.MimeType.IsSet() {
		return true
	}

	return false
}

// SetMimeType gets a reference to the given NullableString and assigns it to the MimeType field.
func (o *OpenGraphFile) SetMimeType(v string) {
	o.MimeType.Set(&v)
}
// SetMimeTypeNil sets the value for MimeType to be an explicit nil
func (o *OpenGraphFile) SetMimeTypeNil() {
	o.MimeType.Set(nil)
}

// UnsetMimeType ensures that no value is present for MimeType, not even an explicit nil
func (o *OpenGraphFile) UnsetMimeType() {
	o.MimeType.Unset()
}

// GetProcessingMetadata returns the ProcessingMetadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenGraphFile) GetProcessingMetadata() bool {
	if o == nil || o.ProcessingMetadata.Get() == nil {
		var ret bool
		return ret
	}
	return *o.ProcessingMetadata.Get()
}

// GetProcessingMetadataOk returns a tuple with the ProcessingMetadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenGraphFile) GetProcessingMetadataOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return o.ProcessingMetadata.Get(), o.ProcessingMetadata.IsSet()
}

// HasProcessingMetadata returns a boolean if a field has been set.
func (o *OpenGraphFile) HasProcessingMetadata() bool {
	if o != nil && o.ProcessingMetadata.IsSet() {
		return true
	}

	return false
}

// SetProcessingMetadata gets a reference to the given NullableBool and assigns it to the ProcessingMetadata field.
func (o *OpenGraphFile) SetProcessingMetadata(v bool) {
	o.ProcessingMetadata.Set(&v)
}
// SetProcessingMetadataNil sets the value for ProcessingMetadata to be an explicit nil
func (o *OpenGraphFile) SetProcessingMetadataNil() {
	o.ProcessingMetadata.Set(nil)
}

// UnsetProcessingMetadata ensures that no value is present for ProcessingMetadata, not even an explicit nil
func (o *OpenGraphFile) UnsetProcessingMetadata() {
	o.ProcessingMetadata.Unset()
}

func (o OpenGraphFile) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Hashes.IsSet() {
		toSerialize["hashes"] = o.Hashes.Get()
	}
	if o.MimeType.IsSet() {
		toSerialize["mimeType"] = o.MimeType.Get()
	}
	if o.ProcessingMetadata.IsSet() {
		toSerialize["processingMetadata"] = o.ProcessingMetadata.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableOpenGraphFile struct {
	value *OpenGraphFile
	isSet bool
}

func (v NullableOpenGraphFile) Get() *OpenGraphFile {
	return v.value
}

func (v *NullableOpenGraphFile) Set(val *OpenGraphFile) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenGraphFile) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenGraphFile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenGraphFile(val *OpenGraphFile) *NullableOpenGraphFile {
	return &NullableOpenGraphFile{value: val, isSet: true}
}

func (v NullableOpenGraphFile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenGraphFile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


