/*
 * Open Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package opengraph

import (
	"encoding/json"
)

// DriveAllOf struct for DriveAllOf
type DriveAllOf struct {
	// Describes the type of drive represented by this resource. Values are \"personal\" for users home spaces, \"projectSpace\" or \"shares\". Read-only.
	DriveType *string `json:"driveType,omitempty"`
	// Describes the status of the drive.
	OCDriveStatus *string `json:"oCDriveStatus,omitempty"`
	// Optional. The user account that owns the drive. Read-only.
	Owner *IdentitySet `json:"owner,omitempty"`
	// Optional. The user account that owns the drive.
	OCCoOwner *IdentitySet `json:"oCCoOwner,omitempty"`
	// Optional. Information about the drive's storage space quota. Read-only.
	Quota *Quota `json:"quota,omitempty"`
	// All items contained in the drive. Read-only. Nullable.
	Items *[]DriveItem `json:"items,omitempty"`
	// The root folder of the drive. Read-only.
	Root *DriveItem `json:"root,omitempty"`
}

// NewDriveAllOf instantiates a new DriveAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDriveAllOf() *DriveAllOf {
	this := DriveAllOf{}
	return &this
}

// NewDriveAllOfWithDefaults instantiates a new DriveAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDriveAllOfWithDefaults() *DriveAllOf {
	this := DriveAllOf{}
	return &this
}

// GetDriveType returns the DriveType field value if set, zero value otherwise.
func (o *DriveAllOf) GetDriveType() string {
	if o == nil || o.DriveType == nil {
		var ret string
		return ret
	}
	return *o.DriveType
}

// GetDriveTypeOk returns a tuple with the DriveType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DriveAllOf) GetDriveTypeOk() (*string, bool) {
	if o == nil || o.DriveType == nil {
		return nil, false
	}
	return o.DriveType, true
}

// HasDriveType returns a boolean if a field has been set.
func (o *DriveAllOf) HasDriveType() bool {
	if o != nil && o.DriveType != nil {
		return true
	}

	return false
}

// SetDriveType gets a reference to the given string and assigns it to the DriveType field.
func (o *DriveAllOf) SetDriveType(v string) {
	o.DriveType = &v
}

// GetOCDriveStatus returns the OCDriveStatus field value if set, zero value otherwise.
func (o *DriveAllOf) GetOCDriveStatus() string {
	if o == nil || o.OCDriveStatus == nil {
		var ret string
		return ret
	}
	return *o.OCDriveStatus
}

// GetOCDriveStatusOk returns a tuple with the OCDriveStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DriveAllOf) GetOCDriveStatusOk() (*string, bool) {
	if o == nil || o.OCDriveStatus == nil {
		return nil, false
	}
	return o.OCDriveStatus, true
}

// HasOCDriveStatus returns a boolean if a field has been set.
func (o *DriveAllOf) HasOCDriveStatus() bool {
	if o != nil && o.OCDriveStatus != nil {
		return true
	}

	return false
}

// SetOCDriveStatus gets a reference to the given string and assigns it to the OCDriveStatus field.
func (o *DriveAllOf) SetOCDriveStatus(v string) {
	o.OCDriveStatus = &v
}

// GetOwner returns the Owner field value if set, zero value otherwise.
func (o *DriveAllOf) GetOwner() IdentitySet {
	if o == nil || o.Owner == nil {
		var ret IdentitySet
		return ret
	}
	return *o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DriveAllOf) GetOwnerOk() (*IdentitySet, bool) {
	if o == nil || o.Owner == nil {
		return nil, false
	}
	return o.Owner, true
}

// HasOwner returns a boolean if a field has been set.
func (o *DriveAllOf) HasOwner() bool {
	if o != nil && o.Owner != nil {
		return true
	}

	return false
}

// SetOwner gets a reference to the given IdentitySet and assigns it to the Owner field.
func (o *DriveAllOf) SetOwner(v IdentitySet) {
	o.Owner = &v
}

// GetOCCoOwner returns the OCCoOwner field value if set, zero value otherwise.
func (o *DriveAllOf) GetOCCoOwner() IdentitySet {
	if o == nil || o.OCCoOwner == nil {
		var ret IdentitySet
		return ret
	}
	return *o.OCCoOwner
}

// GetOCCoOwnerOk returns a tuple with the OCCoOwner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DriveAllOf) GetOCCoOwnerOk() (*IdentitySet, bool) {
	if o == nil || o.OCCoOwner == nil {
		return nil, false
	}
	return o.OCCoOwner, true
}

// HasOCCoOwner returns a boolean if a field has been set.
func (o *DriveAllOf) HasOCCoOwner() bool {
	if o != nil && o.OCCoOwner != nil {
		return true
	}

	return false
}

// SetOCCoOwner gets a reference to the given IdentitySet and assigns it to the OCCoOwner field.
func (o *DriveAllOf) SetOCCoOwner(v IdentitySet) {
	o.OCCoOwner = &v
}

// GetQuota returns the Quota field value if set, zero value otherwise.
func (o *DriveAllOf) GetQuota() Quota {
	if o == nil || o.Quota == nil {
		var ret Quota
		return ret
	}
	return *o.Quota
}

// GetQuotaOk returns a tuple with the Quota field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DriveAllOf) GetQuotaOk() (*Quota, bool) {
	if o == nil || o.Quota == nil {
		return nil, false
	}
	return o.Quota, true
}

// HasQuota returns a boolean if a field has been set.
func (o *DriveAllOf) HasQuota() bool {
	if o != nil && o.Quota != nil {
		return true
	}

	return false
}

// SetQuota gets a reference to the given Quota and assigns it to the Quota field.
func (o *DriveAllOf) SetQuota(v Quota) {
	o.Quota = &v
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *DriveAllOf) GetItems() []DriveItem {
	if o == nil || o.Items == nil {
		var ret []DriveItem
		return ret
	}
	return *o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DriveAllOf) GetItemsOk() (*[]DriveItem, bool) {
	if o == nil || o.Items == nil {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *DriveAllOf) HasItems() bool {
	if o != nil && o.Items != nil {
		return true
	}

	return false
}

// SetItems gets a reference to the given []DriveItem and assigns it to the Items field.
func (o *DriveAllOf) SetItems(v []DriveItem) {
	o.Items = &v
}

// GetRoot returns the Root field value if set, zero value otherwise.
func (o *DriveAllOf) GetRoot() DriveItem {
	if o == nil || o.Root == nil {
		var ret DriveItem
		return ret
	}
	return *o.Root
}

// GetRootOk returns a tuple with the Root field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DriveAllOf) GetRootOk() (*DriveItem, bool) {
	if o == nil || o.Root == nil {
		return nil, false
	}
	return o.Root, true
}

// HasRoot returns a boolean if a field has been set.
func (o *DriveAllOf) HasRoot() bool {
	if o != nil && o.Root != nil {
		return true
	}

	return false
}

// SetRoot gets a reference to the given DriveItem and assigns it to the Root field.
func (o *DriveAllOf) SetRoot(v DriveItem) {
	o.Root = &v
}

func (o DriveAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.DriveType != nil {
		toSerialize["driveType"] = o.DriveType
	}
	if o.OCDriveStatus != nil {
		toSerialize["oCDriveStatus"] = o.OCDriveStatus
	}
	if o.Owner != nil {
		toSerialize["owner"] = o.Owner
	}
	if o.OCCoOwner != nil {
		toSerialize["oCCoOwner"] = o.OCCoOwner
	}
	if o.Quota != nil {
		toSerialize["quota"] = o.Quota
	}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	if o.Root != nil {
		toSerialize["root"] = o.Root
	}
	return json.Marshal(toSerialize)
}

type NullableDriveAllOf struct {
	value *DriveAllOf
	isSet bool
}

func (v NullableDriveAllOf) Get() *DriveAllOf {
	return v.value
}

func (v *NullableDriveAllOf) Set(val *DriveAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableDriveAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableDriveAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDriveAllOf(val *DriveAllOf) *NullableDriveAllOf {
	return &NullableDriveAllOf{value: val, isSet: true}
}

func (v NullableDriveAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDriveAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


