/*
Open Graph API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package opengraph

import (
	"encoding/json"
	"time"
)

// DirectoryObjectAllOf Represents an Active Directory object. The directoryObject type is the base type for many other directory entity types.
type DirectoryObjectAllOf struct {
	DeletedDateTime *time.Time `json:"deletedDateTime,omitempty"`
}

// NewDirectoryObjectAllOf instantiates a new DirectoryObjectAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDirectoryObjectAllOf() *DirectoryObjectAllOf {
	this := DirectoryObjectAllOf{}
	return &this
}

// NewDirectoryObjectAllOfWithDefaults instantiates a new DirectoryObjectAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDirectoryObjectAllOfWithDefaults() *DirectoryObjectAllOf {
	this := DirectoryObjectAllOf{}
	return &this
}

// GetDeletedDateTime returns the DeletedDateTime field value if set, zero value otherwise.
func (o *DirectoryObjectAllOf) GetDeletedDateTime() time.Time {
	if o == nil || o.DeletedDateTime == nil {
		var ret time.Time
		return ret
	}
	return *o.DeletedDateTime
}

// GetDeletedDateTimeOk returns a tuple with the DeletedDateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectoryObjectAllOf) GetDeletedDateTimeOk() (*time.Time, bool) {
	if o == nil || o.DeletedDateTime == nil {
		return nil, false
	}
	return o.DeletedDateTime, true
}

// HasDeletedDateTime returns a boolean if a field has been set.
func (o *DirectoryObjectAllOf) HasDeletedDateTime() bool {
	if o != nil && o.DeletedDateTime != nil {
		return true
	}

	return false
}

// SetDeletedDateTime gets a reference to the given time.Time and assigns it to the DeletedDateTime field.
func (o *DirectoryObjectAllOf) SetDeletedDateTime(v time.Time) {
	o.DeletedDateTime = &v
}

func (o DirectoryObjectAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.DeletedDateTime != nil {
		toSerialize["deletedDateTime"] = o.DeletedDateTime
	}
	return json.Marshal(toSerialize)
}

type NullableDirectoryObjectAllOf struct {
	value *DirectoryObjectAllOf
	isSet bool
}

func (v NullableDirectoryObjectAllOf) Get() *DirectoryObjectAllOf {
	return v.value
}

func (v *NullableDirectoryObjectAllOf) Set(val *DirectoryObjectAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableDirectoryObjectAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableDirectoryObjectAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDirectoryObjectAllOf(val *DirectoryObjectAllOf) *NullableDirectoryObjectAllOf {
	return &NullableDirectoryObjectAllOf{value: val, isSet: true}
}

func (v NullableDirectoryObjectAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDirectoryObjectAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


