/*
Open Graph API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package opengraph

import (
	"encoding/json"
	"time"
)

// DirectoryObjectInline struct for DirectoryObjectInline
type DirectoryObjectInline struct {
	DeletedDateTime *time.Time `json:"deletedDateTime,omitempty"`
}

// NewDirectoryObjectInline instantiates a new DirectoryObjectInline object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDirectoryObjectInline() *DirectoryObjectInline {
	this := DirectoryObjectInline{}
	return &this
}

// NewDirectoryObjectInlineWithDefaults instantiates a new DirectoryObjectInline object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDirectoryObjectInlineWithDefaults() *DirectoryObjectInline {
	this := DirectoryObjectInline{}
	return &this
}

// GetDeletedDateTime returns the DeletedDateTime field value if set, zero value otherwise.
func (o *DirectoryObjectInline) GetDeletedDateTime() time.Time {
	if o == nil || o.DeletedDateTime == nil {
		var ret time.Time
		return ret
	}
	return *o.DeletedDateTime
}

// GetDeletedDateTimeOk returns a tuple with the DeletedDateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectoryObjectInline) GetDeletedDateTimeOk() (*time.Time, bool) {
	if o == nil || o.DeletedDateTime == nil {
		return nil, false
	}
	return o.DeletedDateTime, true
}

// HasDeletedDateTime returns a boolean if a field has been set.
func (o *DirectoryObjectInline) HasDeletedDateTime() bool {
	if o != nil && o.DeletedDateTime != nil {
		return true
	}

	return false
}

// SetDeletedDateTime gets a reference to the given time.Time and assigns it to the DeletedDateTime field.
func (o *DirectoryObjectInline) SetDeletedDateTime(v time.Time) {
	o.DeletedDateTime = &v
}

func (o DirectoryObjectInline) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.DeletedDateTime != nil {
		toSerialize["deletedDateTime"] = o.DeletedDateTime
	}
	return json.Marshal(toSerialize)
}

type NullableDirectoryObjectInline struct {
	value *DirectoryObjectInline
	isSet bool
}

func (v NullableDirectoryObjectInline) Get() *DirectoryObjectInline {
	return v.value
}

func (v *NullableDirectoryObjectInline) Set(val *DirectoryObjectInline) {
	v.value = val
	v.isSet = true
}

func (v NullableDirectoryObjectInline) IsSet() bool {
	return v.isSet
}

func (v *NullableDirectoryObjectInline) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDirectoryObjectInline(val *DirectoryObjectInline) *NullableDirectoryObjectInline {
	return &NullableDirectoryObjectInline{value: val, isSet: true}
}

func (v NullableDirectoryObjectInline) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDirectoryObjectInline) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


